FROM nexus-docker2.sezinno.ru/maven:3.8.5-jdk-8-slim as builder
COPY maven_settings/settings.xml /root/.m2/
RUN mkdir -p /build
WORKDIR /build
COPY pom.xml /build
RUN mvn -B dependency:resolve dependency:resolve-plugins
COPY src /build/src
RUN mvn test
